// app/profile/layout.tsx
"use client";
import DashboardSideBar from "@/component/dashboard/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/app/providers/auth-context";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Profile | Organic",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <DashboardContent>{children}</DashboardContent>
    </AuthProvider>
  );
}

// Separate client component to use hooks
function DashboardContent({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-8">
        <div className="flex flex-col md:flex-row gap-6">
          {/* Sidebar - Hidden on mobile unless toggled */}
          <div className="w-full md:w-1/4 lg:w-1/5">
            <DashboardSideBar />
          </div>

          {/* Main content */}
          <div className="w-full md:w-3/4 lg:w-4/5 bg-white rounded-lg shadow-sm p-6">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
